<template>
  <div class="grid grid-cols-2 gap-6">
    <AInput
      type="text"
      label="Text"
    />
    <AInput
      type="password"
      label="Password"
    />
    <AInput
      type="search"
      label="Search"
    />
    <AInput
      type="number"
      label="Number"
    />
    <AInput
      type="url"
      label="URL"
    />
    <AInput
      type="time"
      label="Time"
    />
    <AInput
      type="date"
      label="Date"
    />
    <AInput
      type="file"
      label="File"
    />
  </div>
</template>
