/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAccordion: typeof import('anu-vue')['AAccordion']
    Demo: typeof import('./src/components/Demo.vue')['default']
    DemoAccordionSimple: typeof import('./src/components/demo/accordion/Simple.vue')['default']
  }
}
