name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          check-latest: true
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install Dependencies
        run: pnpm i

      - name: PNPM build
        run: pnpm run build

      - name: Publish to NPM
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Notify on Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_EMBEDS: |
            [{
                "title": "✨ Anu ${{ github.event.release.tag_name }} has been released!",
                "author": {
                    "name": "${{ github.actor }}",
                    "url": "https://github.com/${{github.actor}}",
                    "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}"
                },
                "url": "${{ github.event.release.html_url }}",
                "description": "Please refer to the release notes for the changes",
                "color": 0
            }]
          DISCORD_AVATAR: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOKS_RELEASE }}
