name: "Test Report"

# on:
#   workflow_run:
#     # runs after CI workflow
#     workflows: ["CI"]
#     types:
#       - completed
on: workflow_dispatch

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: /test-results-(.*)/
          name: "Test report $1"
          path: "*.xml"
          reporter: jest-junit
